services:
  swyh:
    build: .
    volumes:
      - .:/workspace
    stdin_open: true
    network_mode: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]