"""Add Saving Translation Table

Revision ID: c706f3844713
Revises: 5bd3466eabde
Create Date: 2025-07-03 12:05:41.844300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c706f3844713'
down_revision = '5bd3466eabde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_language', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('target_language', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_translation', schema=None) as batch_op:
        batch_op.drop_column('target_language')
        batch_op.drop_column('source_language')

    # ### end Alembic commands ###
