"""Initial user table

Revision ID: d98f904c17a8
Revises: 6230eb472b22
Create Date: 2025-07-02 09:44:53.047608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98f904c17a8'
down_revision = '6230eb472b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('erroneous_translation', sa.Text(), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_report_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_report_timestamp'))

    op.drop_table('translation_report')
    # ### end Alembic commands ###
